name: sanchari
description: "Your Flutter app with Firebase"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_analytics: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/SANCHARI.png
    - assets/images/Background_filler.png

flutter_native_splash:
  color: "#000000"
  android: true
  ios: true
