// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbCwlpmstgDdrrfGCC8JIQuJ5f9K_aOz4',
    appId: '1:1082593076084:web:f5bb2433ca1f0ce83f8221',
    messagingSenderId: '1082593076084',
    projectId: 'gamma-f3b36',
    authDomain: 'gamma-f3b36.firebaseapp.com',
    storageBucket: 'gamma-f3b36.firebasestorage.app',
    measurementId: 'G-K5R4MVG3MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZDagA82r5RbhapX9pkS3U1Mpv9CoQZ8s',
    appId: '1:1082593076084:android:32bf925aa69b2d1b3f8221',
    messagingSenderId: '1082593076084',
    projectId: 'gamma-f3b36',
    storageBucket: 'gamma-f3b36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM21yZ6DERWD7_6D7s4NNvOOj37vsW5qg',
    appId: '1:1082593076084:ios:05eefd0b1f2409243f8221',
    messagingSenderId: '1082593076084',
    projectId: 'gamma-f3b36',
    storageBucket: 'gamma-f3b36.firebasestorage.app',
    androidClientId: '1082593076084-un1rhtqpl8rjd8ad1a7ieovrjfr6ipak.apps.googleusercontent.com',
    iosClientId: '1082593076084-41kejraru75a2uoaflp1as099sfjao0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.newSanchari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM21yZ6DERWD7_6D7s4NNvOOj37vsW5qg',
    appId: '1:1082593076084:ios:05eefd0b1f2409243f8221',
    messagingSenderId: '1082593076084',
    projectId: 'gamma-f3b36',
    storageBucket: 'gamma-f3b36.firebasestorage.app',
    androidClientId: '1082593076084-un1rhtqpl8rjd8ad1a7ieovrjfr6ipak.apps.googleusercontent.com',
    iosClientId: '1082593076084-41kejraru75a2uoaflp1as099sfjao0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.newSanchari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbCwlpmstgDdrrfGCC8JIQuJ5f9K_aOz4',
    appId: '1:1082593076084:web:951407ba7995e83f3f8221',
    messagingSenderId: '1082593076084',
    projectId: 'gamma-f3b36',
    authDomain: 'gamma-f3b36.firebaseapp.com',
    storageBucket: 'gamma-f3b36.firebasestorage.app',
    measurementId: 'G-4NQJ6ENDXT',
  );
}
